<div class="md-footer-social">
  $ if (page.properties.("material.social.web")) $
    <a href="$page.properties.("material.social.web")$" class="md-footer-social__link fa fa-globe"></a>
  $ endif $
  $ if (page.properties.("material.social.github")) $
    <a href="$page.properties.("material.social.github")$" class="md-footer-social__link fa fa-github"></a>
  $ endif $
  $ if (page.properties.("material.social.gitlab")) $
    <a href="$page.properties.("material.social.gitlab")$" class="md-footer-social__link fa fa-gitlab"></a>
  $ endif $
  $ if (page.properties.("material.social.bitbucket")) $
    <a href="$page.properties.("material.social.bitbucket")$" class="md-footer-social__link fa fa-bitbucket"></a>
  $ endif $
  $ if (page.properties.("material.social.linkedin")) $
    <a href="$page.properties.("material.social.linkedin")$" class="md-footer-social__link fa fa-linkedin"></a>
  $ endif $
  $ if (page.properties.("material.social.twitter")) $
    <a href="$page.properties.("material.social.twitter")$" class="md-footer-social__link fa fa-twitter"></a>
  $ endif $
  $ if (page.properties.("material.social.facebook")) $
    <a href="$page.properties.("material.social.facebook")$" class="md-footer-social__link fa fa-facebook"></a>
  $ endif $
</div>
