<a href="$page.properties.("material.repo")$"
   title="Go to repository"
   class="md-source"
   data-md-source="$page.properties.("material.repo.type")$">
  <div class="md-source__icon">
    <i class="fa fa-$page.properties.("material.repo.type")$"></i>
  </div>
  <div class="md-source__repository">
    $page.properties.("material.repo.name"); null="'material.repo.name' not defined"$
  </div>
</a>
