{
      "clipboard.copied": "Copied to clipboard",
      "clipboard.copy": "Copy to clipboard",
      "search.config.lang": "en",
      "search.config.pipeline": "trimmer, stopWordFilter",
      "search.config.separator": "[\\\\s\\\-]+",
      "search.result.none": "No matching documents",
      "search.result.one": "1 matching document",
      "search.result.other": "# matching documents",
      "search.result.placeholder": "Type to start searching"
}